"""Gymnasium environment for the 8-DOF dog, on the modern `mujoco` bindings (not the deprecated `mujoco_py`)."""


import os
import time

import gymnasium as gym
import mujoco
import numpy as np
import yaml
from ament_index_python.packages import get_package_share_directory
from gymnasium import spaces

DOG_DESCRIPTION_SHARE = get_package_share_directory('dog_description')
DEFAULT_MODEL_PATH = os.path.join(DOG_DESCRIPTION_SHARE, 'mjcf', 'dog.mjcf.xml')
# <motor> (torque) actuator variant of DEFAULT_MODEL_PATH, generated by generate_dog_mjcf.py --actuator-type torque
DEFAULT_TORQUE_MODEL_PATH = os.path.join(DOG_DESCRIPTION_SHARE, 'mjcf', 'dog_torque.mjcf.xml')
# <motor>-on-<fixed>-tendon variant, generated by generate_dog_mjcf.py --actuator-type torque_belt.
DEFAULT_TORQUE_BELT_MODEL_PATH = os.path.join(DOG_DESCRIPTION_SHARE, 'mjcf', 'dog_torque_belt.mjcf.xml')
DEFAULT_MOTOR_MAPPING_PATH = os.path.join(DOG_DESCRIPTION_SHARE, 'config', 'motor_mapping.yaml')

# Standing height and STANDING_QPOS_DEG below: measured by hand-posing the robot fully extended in the interactive viewer (mjcf/save_pose.py) and reading qpos back
STAND_HEIGHT_M = 0.313
STAND_HEIGHT_TOLERANCE_M = 0.02  # user: "small range allowed for error"

# STAND + WALK, opt-in via domain_randomization
FLOOR_FRICTION_RANGE = (0.05, 0.8)

# STAND + WALK, opt-in via domain_randomization
PUSH_PROB_PER_STEP = 0.01  # ~1 push/second on average at dt=0.01s
# Real-hardware tilting exceeded what earlier sim push perturbations trained recovery for, so this range was widened to include stronger shoves
PUSH_FORCE_RANGE_N = (10.0, 40.0)  # magnitude range, horizontal only
# Direct torque component (roll/pitch only, not yaw
PUSH_TORQUE_RANGE_NM = (2.0, 10.0)  # magnitude range, roll/pitch only
PUSH_DURATION_S = 0.15  # roughly a real shove, not a sustained force

# Back-leg attachment position domain randomization
BACK_LEG_X_OFFSET_RANGE_M = (0.000, 0.015)  # 5-15mm inward, sampled independently per leg per episode

# Battery position domain randomization battery is physically removable/swappable
BATTERY_Y_JITTER_RANGE_M = 0.005  # +-5mm along the insertion axis

# Overall robot center-of-mass domain randomization user request to add domain randomization to the center of mass of the overall robot).
TORSO_COM_JITTER_XY_RANGE_M = 0.008  # +-8mm, X (left-right) and Y (front-back)
TORSO_COM_JITTER_Z_RANGE_M = 0.003  # +-3mm, Z (up-down)

# Walk task's target torso height, as a fraction of STAND_HEIGHT_M.
WALK_HEIGHT_FRACTION = 0.95

# action_rate_penalty's weight for the STAND task, linearly interpolated by height_progress (0 = sitting, 1 = at standing height
ACTION_RATE_PENALTY_WEIGHT_RISING = -0.1
ACTION_RATE_PENALTY_WEIGHT_STANDING = -0.4

# WALK-only, SEPARATE from STAND's ACTION_RATE_PENALTY_WEIGHT_RISING/ _STANDING above revert EMA and implement two reward-based fixes instead)
WALK_ACTION_RATE_PENALTY_WEIGHT = -0.01

# WALK-only
WALK_HEIGHT_SAG_PENALTY_WEIGHT = 100.0

# WALK-only
WALK_HEIGHT_OVERSHOOT_PENALTY_WEIGHT = 100.0

# _angular_vel_penalty()'s per-task weights
STAND_ANGULAR_VEL_PENALTY_WEIGHT = -0.02
# RAISED 0.2 -> 1.5 into walk_position_hf_v16/walk_home_fv25_v1/fv25_ramp_v1's termination traces
WALK_ANGULAR_VEL_PENALTY_WEIGHT = -1.5

# Weight for -( _torso_pitch_rad() )**2 in the WALK task only
WALK_PITCH_PENALTY_WEIGHT = 3.0

# Weight for -( _torso_roll_rad() )**2 in the WALK task only
WALK_ROLL_PENALTY_WEIGHT = 5.0

# Sigma for roll_gate in _compute_reward_walk() "roll_penalty tuning" round)
WALK_ROLL_GATE_SIGMA_RAD = np.radians(10)

# Bound-only guardrail #1: per-leg ground-contact "foot usage" gate degenerate gaits
WALK_BOUND_MIN_FOOT_DUTY_CYCLE = 0.15
WALK_BOUND_FOOT_USAGE_GATE_SIGMA = 0.10

# Bound-only guardrail #2: per-leg thigh range-of-motion floor same user report
WALK_BOUND_THIGH_ROM_FLOOR_RAD = np.radians(90)
WALK_BOUND_THIGH_ROM_GATE_SIGMA_RAD = np.radians(15)

# Bound-only guardrail #3: per-leg CALF range-of-motion floor direct empirical finding on running_home_s5_ms1000_simple_alr_v10 and running_home_s5_ms1000_whf60_simple_alr_v9's repeated instant-crash failures
WALK_BOUND_CALF_ROM_FLOOR_RAD = np.radians(15)
WALK_BOUND_CALF_ROM_GATE_SIGMA_RAD = np.radians(5)

# Bound-only guardrail #4: per-leg calf joint-limit margin, DURATION-based margin_gate
CALF_JOINT_MARGIN_FLOOR_RAD = np.radians(10)
# GRACE: seconds allowed inside the margin band before it counts against the gate
CALF_JOINT_MARGIN_GRACE_S = 0.08
# Gaussian decay sigma on dwell time PAST the grace period, in seconds (not radians, unlike every other *_GATE_SIGMA_RAD above
CALF_JOINT_MARGIN_GATE_SIGMA_S = 0.35

# Bound-only guardrail #5: front/back leg-pair synchronization, ONLY near full running speed running full speed...
WALK_BOUND_SYMMETRY_GATE_SIGMA = 0.6
# FLOORED (not allowed to reach 0)
WALK_BOUND_SYMMETRY_GATE_FLOOR = 0.5
# Blended in by SPEED RELATIVE TO THE CURRENT CURRICULUM TARGET (reuses forward_progress = forward_velocity_reward / self._walk_forward_ progress_target_m_s, already computed above in this same function), NOT a fixed absolute speed
WALK_BOUND_SYMMETRY_SPEED_RATIO_START = 0.6
WALK_BOUND_SYMMETRY_SPEED_RATIO_FULL = 0.9

# Bound-only guardrail #6: stance-phase straight-leg (kinematic singularity) avoidance PPO_5500000_running_home_s5_ms1000_simple_alr_v1b
STANCE_STRAIGHT_ZONE_RAD = np.radians(25)
# DURATION-based, same reset-on-recovery dwell-time pattern as CALF_JOINT_MARGIN_GRACE_S/_GATE_SIGMA_S above, and for the same reason
STANCE_STRAIGHT_GRACE_S = 0.05
# TIGHTENED 0.3 -> 0.12 PPO_4500000_running_home_s5_ms1000_simple_alr_v1c
STANCE_STRAIGHT_GATE_SIGMA_S = 0.12
# LOWERED 0.5 -> 0.15 (same finding as SIGMA_S above)
STANCE_STRAIGHT_GATE_FLOOR = 0.15

# CALF_STANCE_SIDE_* investigation: leg_a's calf on PPO_6500000_running_home_s5_ms1000_ simple_alr_v1d swept from ~10deg, THROUGH its straight-leg center (~103deg), all the way to ~187deg
CALF_STANCE_SIDE_GRACE_S = 0.03
# TIGHTENED 0.15 -> 0.12, FLOOR 0.3 -> 0.15 report + data investigation: PPO_7500000_running_home_s5_ms1000_ simple_alr_v1e
CALF_STANCE_SIDE_GATE_SIGMA_S = 0.12
CALF_STANCE_SIDE_GATE_FLOOR = 0.15

# CALF_THIGH_TRACKING_*
CALF_THIGH_TRACKING_THIGH_QVEL_FLOOR_RAD_S = np.radians(20)
CALF_THIGH_TRACKING_MIN_CALF_FRACTION = 0.2
CALF_THIGH_TRACKING_GRACE_S = 0.05
CALF_THIGH_TRACKING_GATE_SIGMA_S = 0.2
CALF_THIGH_TRACKING_GATE_FLOOR = 0.3

# Deliberate forward-lean reward target
WALK_TARGET_PITCH_RAD = np.radians(10)

# Built-in forward lean for the 'home' reset pose itself following investigation into "no_stiffness_slew_100/ _200: still falling backward despite WALK_TARGET_PITCH_RAD"
HOME_START_FORWARD_LEAN_RAD = np.radians(8)

# Height offset paired with HOME_START_FORWARD_LEAN_RAD above bug found the same day the lean was added
HOME_START_LEAN_HEIGHT_OFFSET_M = 0.05

# Weight for rise_backward_pitch_penalty in _compute_reward_walk()
WALK_RISE_BACKWARD_PITCH_PENALTY_WEIGHT = 5.0

# pitch_gate's sigma (see pitch_penalty's comment/pitch_gate's own comment in _compute_reward_walk() for the full mechanism)
WALK_PITCH_GATE_SIGMA_RAD = np.radians(15)

# WALK-only, added straight"
WALK_LATERAL_VEL_PENALTY_WEIGHT = 5.0
WALK_YAW_RATE_PENALTY_WEIGHT = 2.0

# WALK-wide (not is_stand_and_walk-scoped, same as the two weights above)
WALK_HEADING_DEVIATION_PENALTY_WEIGHT = 4.0

# WALK-wide diagnostic + swing-time-fairness" investigation) after dropping trot_symmetry_reward (see that term's DROPPED comment in the return statement below) left a real gap: v27's per-leg diagnostic showed leg_c (back-right) stuck at ~80-85% ground-contact share by 3M-5M steps (vs ~55-65% for the other three), timing its brief lifts right at FEET_STANCE_TIME_MAX_S's 0.3s cap rather than taking a genuine ~0.3s swing like the other legs
SWING_FAIRNESS_EMA_ALPHA = 0.02
SWING_FAIRNESS_TARGET_DUTY_CYCLE = 0.75
SWING_FAIRNESS_GATE_START = 0.2
SWING_FAIRNESS_GATE_FULL = 0.4
WALK_SWING_FAIRNESS_WEIGHT = 5.0

# front_clearance_reward/back_clearance_reward "three follow-up asks...
WALK_FRONT_CLEARANCE_WEIGHT = 2.0
# RAISED 2.0 -> 3.0 clearance: user wants MORE than the current split fix gives" round)
WALK_BACK_CLEARANCE_WEIGHT = 3.0

# Back legs' own higher foot-clearance target
BACK_FOOT_CLEARANCE_TARGET_M = 0.08

# Gate for back_clearance_reward specifically
WALK_BACK_CLEARANCE_GATE_START = 0.2
WALK_BACK_CLEARANCE_GATE_FULL = 0.4

# swing_amplitude_penalty proposing a new swing-AMPLITUDE-discrepancy term (front vs back)).
WALK_SWING_AMPLITUDE_PENALTY_WEIGHT = 3.0

# Absolute per-leg deadzone for swing_amplitude_penalty (see that term's own comment/WALK_SWING_AMPLITUDE_PENALTY_WEIGHT above)
SWING_AMPLITUDE_MAX_DEVIATION_RAD = np.radians(70)

# calf_amplitude_penalty "calf tuck persists after the thigh-amplitude fix worked").
WALK_CALF_ACTIVITY_PENALTY_WEIGHT = 3.0
CALF_ACTIVITY_WINDOW_TICKS = 50

# RAISED 20deg -> 35deg "forward_tilt_walk_v1@4M checkpoint check"): measured directly on forward_tilt_walk_v1@4M that leg_d's calf ROM (25.5deg) clears the old 20deg floor cleanly, reading exactly zero penalty, despite being notably smaller than the other three legs' 42-51deg
CALF_ACTIVITY_MIN_RANGE_RAD = np.radians(35)

# JOINT_LIMIT_MARGIN_PENALTY_WEIGHT/_joint_limit_margin_penalty() REMOVED jointlimit_probe_v1 real deployment" review).

# STAND+WALK ONLY (walk_start_pose='random')
WALK_CLIMB_GATE_THRESHOLD = 0.8

# STAND+WALK ONLY (walk_start_pose='random')
WALK_STAND_HOLD_S = 2.0

# STAND+WALK ONLY following "stand, hold X seconds" review): the first draft reused WALK_CLIMB_GATE_THRESHOLD (0.8) to also start the hold-timer
WALK_STAND_HOLD_THRESHOLD = 0.884

# STAND+WALK ONLY, added alongside the WALK_STAND_HOLD_THRESHOLD loosening above : even at the loosened 0.884 threshold, a plain instant-reset-on-dip still capped continuous holds around 0.5-0.66s
WALK_STAND_HOLD_DIP_GRACE_S = 0.2

# Reference forward speed (m/s) for gating WALK's upright_reward
WALK_FORWARD_PROGRESS_TARGET_M_S = 0.15

# Weight for _trot_symmetry_reward().
WALK_TROT_SYMMETRY_WEIGHT = 2.5

# _bound_symmetry_reward()'s weight/gate genuine running with an aerial phase, not just faster trotting, see gait_style's own comment
WALK_BOUND_SYMMETRY_WEIGHT = 5.0
WALK_BOUND_SYMMETRY_GATE_START = 0.2
WALK_BOUND_SYMMETRY_GATE_FULL = 0.4

# WALK-specific RESIDUAL action space reference repos in this workspace (quadrupeds_locomotion/friend_code), which structure their action as target = default_pose + action_scale*residual rather than an absolute target the way this project's action space always has been.
WALK_ACTION_RESIDUAL_RANGE_RAD = np.radians(150)

# Interpolate the WALK residual-action baseline from 'home' (all-zero, in this belt-compensated absolute-action space) to the full standing target (_walk_default_action_rad) smoothly over this many seconds at the START of a 'home'-start episode, instead of the baseline being _walk_default_action_rad from tick 0 "Analysis of Issue.md" investigation and its "Rise Asymmetry Fix").
HOME_RISE_INTERPOLATION_DURATION_S = 0.75
# Sitting/home height (see FALL_HEIGHT_M's comment)
SIT_HEIGHT_M = 0.14

# Motor-id order (1..8), hand-verified sim qpos at the standing pose above (NOT converted from real hardware degrees).
STANDING_QPOS_DEG = np.array([107.507, 104.071, -86.789, -98.804, 98.743, 98.011, -93.049, -103.804])

# Motor-order (0-indexed, i.e.
SYMMETRIC_THIGH_IDX = [0, 3, 4, 7]  # motors 1, 4, 5, 8 (leg_a, leg_b, leg_c, leg_d)
# [1,-1,1,-1] since the : sim's raw directions now match the real robot motor-for-motor, and the real robot's left/right motors are mirror-mounted
THIGH_SYMMETRY_SIGN = np.array([1, -1, 1, -1])
SYMMETRIC_CALF_IDX = [1, 2, 5, 6]   # motors 2, 3, 6, 7 (leg_a, leg_b, leg_c, leg_d)
# [1,-1,1,-1] since the same AXIS_FLIP (was [-1,-1,1,1] under the old axes): "calf towards front" is now POSITIVE qpos for the right legs' calves (a, c) and NEGATIVE for the left legs' (b, d), matching the real robot's mirror-mounted motors
CALF_SYMMETRY_SIGN = np.array([1, -1, 1, -1])
# NOT YET AUDITED (flagged : _compute_reward_stand() computes calf_spread from self.data.qpos directly

# Sitting/home height settles around 0.14m (measured the same way as STAND_HEIGHT_M, at qpos=0)
FALL_HEIGHT_M = 0.10
MAX_TILT_RAD = 0.9  # ~51 degrees from vertical before an episode ends
# WALK-specific, MUCH tighter tilt termination by two reference quadruped-RL repos (quadrupeds_locomotion/friend_code in this workspace), both of which terminate hard on tilt (10deg and 45deg respectively) rather than relying only on a soft reward penalty the way this project's WALK_PITCH_PENALTY_WEIGHT/ WALK_ANGULAR_VEL_PENALTY_WEIGHT do.
WALK_MAX_TILT_RAD = np.radians(20)

# Soft-trigger termination on prolonged knee/thigh/shin contact
NONTIP_TERMINATION_ENABLED = True
# LOWERED 1.0 -> 0.5 : checked directly against walk_policy_home_v11/v12
NONTIP_TERMINATION_S = 0.0
# STANDING-start gets its OWN threshold request): the 2.0s value above exists specifically to cover 'home's own reset-time penetration violence (see the comment right above)
NONTIP_TERMINATION_S_STANDING = 0.0

# BOUND ONLY
NONTIP_TERMINATION_S_BOUND = 0.0

# Hard cutoff for _knee_walking_too_long()'s gate same review as NONTIP_TERMINATION_S's fix above
NONTIP_TERMINATION_MIN_RISE_HEIGHT_M = 0.19460596

# STAND only user request: measured directly that the instant/zero-grace version terminates ~20 ticks in on average under PPO's normal STOCHASTIC exploration noise, EVERY episode, 20/20
STAND_AIRBORNE_TERMINATION_S = 3.0

MAX_EPISODE_STEPS = 1000
NUM_MOTORS = 8

# Per-motor max target slew rate, applied every step()
MAX_SLEW_DEG_PER_S = 1000.0

# Curriculum end target for SlewCurriculumCallback (train.py)
SLEW_CURRICULUM_TARGET_DEG_PER_S = 250.0

# EMA output-smoothing filter TRIED AND REVERTED investigation titled "the alpha=0.3 fix made things worse").

# TORQUE mode only : velocity damping, applied in step() as ctrl = action - TORQUE_KD_GAIN*qvel
TORQUE_KD_GAIN = 0.2

# TORQUE_BELT mode only : PD gains for the automatic calf belt-compensation servo applied in step()'s control_mode='torque_belt' branch, ON TOP of (not replacing) the policy's own calf torque
BELT_SERVO_KP = 30.0
BELT_SERVO_KD = 2.0

# TORQUE_BELT mode only : per-tick adaptation rate for self._belt_target_abs_calf
BELT_TARGET_ADAPT_RATE_STAND = 0.02
BELT_TARGET_ADAPT_RATE_WALK = 0.15

# Real-hardware-realistic SENSOR noise (motor position/velocity + IMU), opt-in via domain_randomization
MOTOR_POS_NOISE_STD_RAD = np.radians(0.1)     # ~0.1deg encoder noise
MOTOR_VEL_NOISE_STD_RAD_S = np.radians(0.5)   # velocity noisier than position (often derived by differentiating)
ACCEL_NOISE_STD_M_S2 = 0.05
GYRO_NOISE_STD_RAD_S = 0.01

# How close a ground contact must be to a leg's foot site to count as "standing on the foot" rather than "standing on the knee/shin"
FOOT_CONTACT_RADIUS_M = 0.03

# Target foot height (world z, meters) during swing phase for _foot_clearance_reward()
FOOT_CLEARANCE_TARGET_M = 0.06

# sigma for _foot_clearance_reward()'s Gaussian
FOOT_CLEARANCE_SIGMA_M = FOOT_CLEARANCE_TARGET_M / 2

# RAISED 0.1 -> 3.0 on for 3 seconds in the air")
FEET_AIR_TIME_TARGET_S = 0.1

# Cap (seconds) beyond which a currently-airborne leg starts accruing a GROWING per-tick penalty in _feet_air_time_reward(), even before it ever lands.
FEET_AIR_TIME_MAX_S = 3.0 * FEET_AIR_TIME_TARGET_S

# Mirror image of FEET_AIR_TIME_MAX_S: cap (seconds) beyond which a currently-PLANTED leg starts accruing a GROWING per-tick penalty in _feet_air_time_reward(), even before it ever swings.
FEET_STANCE_TIME_MAX_S = 0.3

# _trot_symmetry_reward()'s stuck-phase gate : a leg that's held the SAME contact state (grounded or swinging, via self._leg_phase_time) longer than this returns the worst possible score regardless of the instantaneous 4-leg pattern
MAX_LEG_PHASE_S = 0.5

# _calf_swing_motion_reward()'s ceiling : that reward is mean squared calf angular velocity (rad/s)^2 across swinging legs, with NO upper bound before this
CALF_SWING_REWARD_CAP = 4.0

# Three additional WALK-only early-termination conditions user request: training was wasting clock time letting clearly-doomed "leaning forward and dragging" episodes run for another 100+ ticks before the existing _is_fallen()/_knee_walking_too_long() eventually caught them).

# _leg_stuck_too_long()'s threshold: reuses self._leg_phase_time (already tracked for _trot_symmetry_reward()'s MAX_LEG_PHASE_S gate above) as a hard termination too.
LEG_PHASE_TERMINATION_S = 3.0

# _pitch_diverging_too_long()'s thresholds: catches a torso that's leaning and NOT recovering well before it reaches the much larger absolute WALK_MAX_TILT_RAD (~20deg) _is_fallen() threshold
PITCH_TERMINATION_FORWARD_RAD = np.radians(25)
PITCH_TERMINATION_BACKWARD_RAD = np.radians(-5)
PITCH_TERMINATION_DURATION_S = 0.5

# WALK only
WALK_FALL_TERMINAL_PENALTY = -10.0

# _no_forward_progress()'s thresholds: a general backstop distinct from the two failure-mode-specific checks above
NO_PROGRESS_GRACE_S = 4.5
NO_PROGRESS_MIN_DISTANCE_M = 0.05


def load_motor_joint_names(motor_mapping_path=DEFAULT_MOTOR_MAPPING_PATH):
    """Returns MJCF joint names ["leg_a_thigh", ...] indexed motor 1..8, resolved from motor_mapping.yaml's {leg, joint} pairs"""

    with open(motor_mapping_path) as f:
        mapping = yaml.safe_load(f)['motors']
    return [
        f"{mapping[motor_id]['leg']}_{mapping[motor_id]['joint']}"
        for motor_id in range(1, NUM_MOTORS + 1)
    ]


class DogEnv(gym.Env):
    metadata = {'render_modes': ['human'], 'render_fps': 50}

    def __init__(self, model_path=None,
                 motor_mapping_path=DEFAULT_MOTOR_MAPPING_PATH,
                 render_mode=None, domain_randomization=False, task='stand',
                 walk_start_pose='standing', walk_height_fraction=WALK_HEIGHT_FRACTION,
                 control_mode='position', position_kp=None, position_kd=None,
                 position_kp_range=None, position_kd_range=None, home_start_prob=0.0,
                 max_slew_deg_per_s=None, walk_forward_progress_target_m_s=None,
                 gait_style='trot', joint_stiffness=None):
        super().__init__()
        if task not in ('stand', 'walk'):
            raise ValueError(f"task must be 'stand' or 'walk', got {task!r}")
        # 'position' (default, unchanged): <position> PD actuators, action = target joint angle
        if control_mode not in ('position', 'torque', 'torque_belt'):
            raise ValueError(
                f"control_mode must be 'position', 'torque', or 'torque_belt', got {control_mode!r}")
        self.control_mode = control_mode
        # A fixed gain and a randomized range are mutually exclusive
        if (position_kp is not None or position_kd is not None) and \
                (position_kp_range is not None or position_kd_range is not None):
            raise ValueError(
                'Pass either position_kp/position_kd (fixed) or position_kp_range/'
                'position_kd_range (randomized per episode), not both.')
        if model_path is None:
            # torque_belt gets its OWN model file (DEFAULT_TORQUE_BELT_ MODEL_PATH, generate_dog_mjcf.py --actuator-type torque_belt)
            model_path = {
                'torque': DEFAULT_TORQUE_MODEL_PATH,
                'torque_belt': DEFAULT_TORQUE_BELT_MODEL_PATH,
            }.get(control_mode, DEFAULT_MODEL_PATH)
        # WALK-only parameter instead of a hardcoded constant).
        self._walk_target_height_m = walk_height_fraction * STAND_HEIGHT_M
        # WALK-only approach of training one policy to climb from home AND walk, rather than assuming a separate stand policy always runs first).
        if walk_start_pose not in ('standing', 'home', 'random'):
            raise ValueError(
                f"walk_start_pose must be 'standing', 'home', or 'random', got {walk_start_pose!r}")
        self.walk_start_pose = walk_start_pose
        # Probability reset() picks 'home' over 'standing' when walk_start_pose='random'
        self._home_start_prob = home_start_prob
        # Per-episode-independent (unlike position_kp_range/home_start_prob above): step()'s slew clamp reads this fresh every single step, not just at reset(), so set_max_slew_deg_per_s() below takes effect immediately, not on the next episode
        self._max_slew_deg_per_s = (
            max_slew_deg_per_s if max_slew_deg_per_s is not None else MAX_SLEW_DEG_PER_S)
        # walk_forward_progress_target_m_s "start creating what we need to train...
        self._walk_forward_progress_target_m_s = (
            walk_forward_progress_target_m_s if walk_forward_progress_target_m_s is not None
            else WALK_FORWARD_PROGRESS_TARGET_M_S)
        # gait_style trot, all 4 legs off the ground"): WALK-only, picks which gait- pattern reward _compute_reward_walk() uses
        if gait_style not in ('trot', 'bound'):
            raise ValueError(f"gait_style must be 'trot' or 'bound', got {gait_style!r}")
        self.gait_style = gait_style
        self.task = task
        # torque_belt only
        self._belt_target_adapt_rate = (
            BELT_TARGET_ADAPT_RATE_WALK if task == 'walk' else BELT_TARGET_ADAPT_RATE_STAND)
        self.model_path = model_path
        self.render_mode = render_mode
        self.domain_randomization = domain_randomization

        self.model = mujoco.MjModel.from_xml_path(self.model_path)
        self.data = mujoco.MjData(self.model)

        # position_kp/position_kd : runtime override of the MJCF's baked-in <position> actuator gains (generate_dog_mjcf.py --kp/--kv, default 60/4
        if control_mode == 'position' and position_kp is not None and position_kd is not None:
            self._apply_position_gains(position_kp, position_kd)
        self.position_kp = position_kp
        self.position_kd = position_kd

        # position_kp_range/position_kd_range domain randomization + curriculum over position_kp/position_kd, not just a single fixed override): each tuple is (low, high); when set, reset() below samples a FRESH kp/kd uniformly from the CURRENT range every episode (not once at construction), so the same training run sees a spread of servo stiffnesses instead of committing to one value for its whole lifetime
        self._position_kp_range = position_kp_range
        self._position_kd_range = position_kd_range

        self.renderer = None
        self._paused = False

        self.torso_body_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, 'torso')
        self.floor_geom_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_GEOM, 'floor')
        self.torso_geom_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_GEOM, 'torso_body')
        self.default_floor_friction = self.model.geom_friction[self.floor_geom_id].copy()

        # Back-leg attachment offset domain randomization see BACK_LEG_X_OFFSET_RANGE_M's comment)
        self.leg_c_thigh_body_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, 'leg_c_thigh')
        self.leg_d_thigh_body_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, 'leg_d_thigh')
        self.default_leg_c_thigh_pos = self.model.body_pos[self.leg_c_thigh_body_id].copy()
        self.default_leg_d_thigh_pos = self.model.body_pos[self.leg_d_thigh_body_id].copy()

        # Battery position domain randomization BATTERY_Y_JITTER_RANGE_M's comment)
        self.battery_body_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, 'battery_mass')
        self.default_battery_pos = self.model.body_pos[self.battery_body_id].copy()

        # Overall robot CoM domain randomization TORSO_COM_JITTER_XY_RANGE_M's comment)
        self.default_torso_ipos = self.model.body_ipos[self.torso_body_id].copy()

        # Each leg's collision capsule is named "<leg>_calf" (same name as the calf joint, different MuJoCo namespace) and runs knee->foot as ONE capsule (no separate foot geom)
        self.calf_geom_ids = [
            mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_GEOM, f'{leg}_calf')
            for leg in ('leg_a', 'leg_b', 'leg_c', 'leg_d')
        ]
        # Added distinct contact geom this project's contact-checking logic previously never looked at at all (only ever checked calf_geom_ids)
        self.thigh_geom_ids = [
            mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_GEOM, f'{leg}_thigh')
            for leg in ('leg_a', 'leg_b', 'leg_c', 'leg_d')
        ]
        self.foot_site_ids = [
            mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_SITE, f'{leg}_foot')
            for leg in ('leg_a', 'leg_b', 'leg_c', 'leg_d')
        ]

        # control_mode='torque_belt' only : the 4 <fixed> tendons DEFAULT_TORQUE_BELT_MODEL_PATH defines, each equal to one leg's calf ABSOLUTE (belt-decoupled) angle
        self.calf_tendon_ids = [
            mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_TENDON, f'{leg}_calf_absolute')
            for leg in ('leg_a', 'leg_b', 'leg_c', 'leg_d')
        ]

        # motor_1..motor_8 -> this joint's qpos/qvel address, so the observation is built in a fixed, motor-id order regardless of the MJCF's body-tree traversal order.
        joint_names = load_motor_joint_names(motor_mapping_path)
        self.motor_qpos_adr = np.array(
            [self.model.joint(name).qposadr[0] for name in joint_names])
        self.motor_dof_adr = np.array(
            [self.model.joint(name).dofadr[0] for name in joint_names])

        # joint_stiffness user request
        self._thigh_joint_ids = np.array([
            self.model.joint(name).id for name in joint_names if name.endswith('_thigh')])
        if joint_stiffness is not None:
            self._apply_joint_stiffness(joint_stiffness)
        self.joint_stiffness = joint_stiffness

        # Belt/pulley coupling compensation (real robot confirmed : each leg's calf motor drives its lower pulley through a timing belt to an upper pulley mounted on the (non-rotating-with-the-thigh) torso/shoulder; the lower pulley itself free-spins on a bearing relative to the thigh.
        self.calf_idx = np.array(
            [i for i, n in enumerate(joint_names) if n.endswith('_calf')])
        self.calf_thigh_idx = np.array([
            joint_names.index(joint_names[i][:-len('_calf')] + '_thigh')
            for i in self.calf_idx
        ])
        self.calf_thigh_qpos_adr = self.motor_qpos_adr[self.calf_thigh_idx]
        self.calf_thigh_dof_adr = self.motor_dof_adr[self.calf_thigh_idx]

        # Per-leg RAW calf joint hard limits (rad), same self.calf_idx order as self._calf_hinge_window's columns
        calf_joint_ranges = np.array(
            [self.model.joint(joint_names[i]).range for i in self.calf_idx])
        self._calf_joint_range_lo = calf_joint_ranges[:, 0]
        self._calf_joint_range_hi = calf_joint_ranges[:, 1]
        # Per-leg straight-leg (max hip-to-foot extension) calf qpos
        self._calf_straight_center_rad = (
            self._calf_joint_range_lo + self._calf_joint_range_hi) / 2.0

        calf_belt_sign = []
        for i in self.calf_idx:
            calf_joint_id = self.model.joint(joint_names[i]).id
            hip_joint_id = self.model.joint(joint_names[joint_names.index(
                joint_names[i][:-len('_calf')] + '_thigh')]).id
            calf_body_id = self.model.jnt_bodyid[calf_joint_id]
            knee_axis_in_thigh_frame = np.zeros(3)
            mujoco.mju_rotVecQuat(
                knee_axis_in_thigh_frame, self.model.jnt_axis[calf_joint_id],
                self.model.body_quat[calf_body_id])
            same_direction = np.dot(knee_axis_in_thigh_frame, self.model.jnt_axis[hip_joint_id]) > 0
            calf_belt_sign.append(-1.0 if same_direction else 1.0)
        self.calf_belt_sign = np.array(calf_belt_sign)

        # WALK's residual-action baseline (see WALK_ACTION_RESIDUAL_RANGE_RAD's comment)
        walk_default_rad = np.radians(STANDING_QPOS_DEG).copy()
        walk_default_rad[self.calf_idx] -= (
            self.calf_belt_sign * np.radians(STANDING_QPOS_DEG)[self.calf_thigh_idx])
        self._walk_default_action_rad = walk_default_rad.astype(np.float32)

        # NOTE: for calf motors, this is the raw MJCF actuator's thigh-relative ctrlrange, used as-is for the ABSOLUTE action space too (see calf_idx's comment above)
        ctrlrange = self.model.actuator_ctrlrange.copy()
        if self.control_mode in ('torque', 'torque_belt'):
            # Direct torque control (see control_mode's comment in __init__)
            self.action_space = spaces.Box(
                low=ctrlrange[:, 0].astype(np.float32),
                high=ctrlrange[:, 1].astype(np.float32),
                dtype=np.float32)
        elif self.task == 'walk':
            # RESIDUAL action space
            self.action_space = spaces.Box(
                low=-WALK_ACTION_RESIDUAL_RANGE_RAD,
                high=WALK_ACTION_RESIDUAL_RANGE_RAD,
                shape=(NUM_MOTORS,), dtype=np.float32)
        else:
            self.action_space = spaces.Box(
                low=ctrlrange[:, 0].astype(np.float32),
                high=ctrlrange[:, 1].astype(np.float32),
                dtype=np.float32)

        self.prev_action = np.zeros(NUM_MOTORS, dtype=np.float32)
        # Per-leg (leg_a..leg_d order) seconds spent airborne since that leg's last ground contact
        self._feet_air_time = np.zeros(4)
        # Mirror image: seconds spent PLANTED since that leg's last
        # swing -- see FEET_STANCE_TIME_MAX_S's comment.
        self._feet_stance_time = np.zeros(4)
        # Per-leg seconds spent in CONTINUOUS non-tip (knee/shin) contact
        # -- see NONTIP_TERMINATION_S's comment / _knee_walking_too_long().
        self._non_tip_contact_time = np.zeros(4)
        # BOUND ONLY
        self._torso_contact_time = 0.0
        # BOUND ONLY
        self._calf_margin_time = np.zeros(4)
        # BOUND ONLY
        self._calf_stance_straight_time = np.zeros(4)
        # BOUND ONLY
        self._calf_stance_entry_side = np.zeros(4)
        self._calf_wrong_side_time = np.zeros(4)
        self._prev_in_stance = np.zeros(4, dtype=bool)
        # BOUND ONLY
        self._calf_poor_tracking_time = np.zeros(4)
        # Per-leg seconds spent in CONTINUOUS full airborne (no contact at all)
        self._airborne_time = np.zeros(4)
        # STAND+WALK ONLY
        self._standing_hold_time = 0.0
        # STAND+WALK ONLY
        self._standing_hold_dip_time = 0.0
        # Push perturbation state (STAND + WALK)
        self._push_remaining_s = 0.0
        self._push_force = np.zeros(3)
        self._push_torque = np.zeros(3)
        # Per-leg seconds since that leg's contact state (grounded vs swinging) last CHANGED, either direction
        self._leg_phase_time = np.zeros(4)
        self._prev_leg_contact = np.zeros(4, dtype=bool)
        # Per-leg SLOW EMA (SWING_FAIRNESS_EMA_ALPHA) of ground-contact state (1.0 = grounded, 0.0 = airborne)
        self._contact_duty_cycle = np.zeros(4)
        # True sliding-window buffer of RAW calf hinge angle (rad), shape (CALF_ACTIVITY_WINDOW_TICKS, 4)
        self._calf_hinge_window = np.zeros((CALF_ACTIVITY_WINDOW_TICKS, 4))
        self._calf_hinge_window_idx = 0
        # Same true-sliding-window pattern as self._calf_hinge_window above, RAW thigh qpos instead of calf
        self._thigh_hinge_window = np.zeros((CALF_ACTIVITY_WINDOW_TICKS, 4))
        self._thigh_hinge_window_idx = 0
        # Seconds torso pitch magnitude has stayed continuously above PITCH_TERMINATION_THRESHOLD_RAD
        self._high_pitch_time = 0.0
        # World +y torso position at episode start
        self._episode_start_y = 0.0
        # Torso heading (yaw) at episode start
        self._episode_start_yaw = 0.0

        # motor qpos (8) + motor qvel (8) + IMU sensordata + prev_action (8)
        self.single_obs_dim = NUM_MOTORS + NUM_MOTORS + self.model.nsensordata + NUM_MOTORS
        self.obs_history_len = 3
        obs_dim = self.single_obs_dim * self.obs_history_len
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(obs_dim,), dtype=np.float32)
        self._obs_history = np.zeros(obs_dim, dtype=np.float32)

        self._step_count = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        mujoco.mj_resetData(self.model, self.data)
        self.prev_action = np.zeros(NUM_MOTORS, dtype=np.float32)
        self._feet_air_time = np.zeros(4)
        self._feet_stance_time = np.zeros(4)
        self._non_tip_contact_time = np.zeros(4)
        self._torso_contact_time = 0.0
        self._calf_margin_time = np.zeros(4)
        self._calf_stance_straight_time = np.zeros(4)
        self._calf_stance_entry_side = np.zeros(4)
        self._calf_wrong_side_time = np.zeros(4)
        self._prev_in_stance = np.zeros(4, dtype=bool)
        self._calf_poor_tracking_time = np.zeros(4)
        self._airborne_time = np.zeros(4)
        # STAND+WALK ONLY
        self._standing_hold_time = 0.0
        # STAND+WALK ONLY
        self._standing_hold_dip_time = 0.0
        # Push perturbation state (STAND + WALK)
        self._push_remaining_s = 0.0
        self._push_force = np.zeros(3)
        self._push_torque = np.zeros(3)
        self._leg_phase_time = np.zeros(4)
        self._prev_leg_contact = np.zeros(4, dtype=bool)
        self._contact_duty_cycle = np.zeros(4)
        self._high_pitch_time = 0.0
        self._step_count = 0
        # _climb_progress()/_get_rise_progress() reference see HOME_START_LEAN_HEIGHT_OFFSET_M's own comment)
        self._rise_progress_height_offset = 0.0

        if self.task == 'walk':
            # 'random' (see walk_start_pose's __init__ comment): sample THIS episode's actual start pose now, once, then use that sampled value (not self.walk_start_pose directly) for both branches below
            if self.walk_start_pose == 'random':
                episode_start_pose = (
                    'home' if self.np_random.uniform() < self._home_start_prob else 'standing')
            else:
                episode_start_pose = self.walk_start_pose
            # Stored for step()
            self._episode_start_pose = episode_start_pose
            if episode_start_pose == 'standing':
                # Start already standing
                qpos_rad = np.radians(STANDING_QPOS_DEG)
            else:
                # 'home' : start from the sitting/home pose instead, same starting state STAND's task uses
                qpos_rad = np.zeros(NUM_MOTORS)
            if self.domain_randomization:
                qpos_rad = qpos_rad + self.np_random.uniform(-0.02, 0.02, size=NUM_MOTORS)
            self.data.qpos[self.motor_qpos_adr] = qpos_rad
            # step()'s slew-rate limiter clips each new action around prev_action
            if self.control_mode == 'position':
                prev_action = qpos_rad.copy()
                prev_action[self.calf_idx] -= self.calf_belt_sign * qpos_rad[self.calf_thigh_idx]
                self.prev_action = prev_action.astype(np.float32)
            if episode_start_pose == 'standing':
                # The free joint's own z (qpos[2]) still defaults to the model's qpos=0 spawn height (0.287m, chosen to clear the floor at the CAD-captured/sitting leg pose)
                self.data.qpos[2] = STAND_HEIGHT_M
            else:
                # 'home' very first ~16 ticks were pure free-fall, all 4 feet 'air', height dropping smoothly 0.287->~0.15m with ZERO ground contact the whole time, before the policy had any physical grounding to act from
                self.data.qpos[2] = SIT_HEIGHT_M
                # HOME_START_FORWARD_LEAN_RAD : bias the free joint's own orientation, not just height
                half = HOME_START_FORWARD_LEAN_RAD / 2.0
                self.data.qpos[3:7] = [np.cos(-half), np.sin(-half), 0.0, 0.0]
        elif self.task == 'stand':
            # FIXED up from a sitting position ON THE GROUND, will this still work?"): motor qpos is already 0 (mj_resetData's default), but the free joint's z (qpos[2]) was previously left at the model's raw qpos=0 spawn height (0.287m, chosen only to clear the floor at the CAD pose, not the real settled height)
            self.data.qpos[2] = SIT_HEIGHT_M

        if self.domain_randomization:
            self._randomize_ground()
        else:
            self.model.geom_friction[self.floor_geom_id] = self.default_floor_friction

        # Back-leg attachment offset
        for leg, body_id, default_pos, sign in (
            ('leg_c', self.leg_c_thigh_body_id, self.default_leg_c_thigh_pos, -1.0),
            ('leg_d', self.leg_d_thigh_body_id, self.default_leg_d_thigh_pos, 1.0),
        ):
            new_pos = default_pos.copy()
            if self.domain_randomization:
                offset = self.np_random.uniform(*BACK_LEG_X_OFFSET_RANGE_M)
                new_pos[0] += sign * offset  # x = model's shoulder/left-right axis
            self.model.body_pos[body_id] = new_pos

        # Battery position jitter
        if self.domain_randomization:
            battery_pos = self.default_battery_pos.copy()
            battery_pos[1] += self.np_random.uniform(
                -BATTERY_Y_JITTER_RANGE_M, BATTERY_Y_JITTER_RANGE_M)
            self.model.body_pos[self.battery_body_id] = battery_pos
        else:
            self.model.body_pos[self.battery_body_id] = self.default_battery_pos

        # Overall robot CoM jitter
        if self.domain_randomization:
            com_jitter = np.array([
                self.np_random.uniform(-TORSO_COM_JITTER_XY_RANGE_M, TORSO_COM_JITTER_XY_RANGE_M),
                self.np_random.uniform(-TORSO_COM_JITTER_XY_RANGE_M, TORSO_COM_JITTER_XY_RANGE_M),
                self.np_random.uniform(-TORSO_COM_JITTER_Z_RANGE_M, TORSO_COM_JITTER_Z_RANGE_M),
            ])
            self.model.body_ipos[self.torso_body_id] = self.default_torso_ipos + com_jitter
        else:
            self.model.body_ipos[self.torso_body_id] = self.default_torso_ipos

        # position_kp_range/position_kd_range (see __init__'s comment): fresh sample every episode from whatever the CURRENT range bounds are (may have been widened since the last episode by a training callback via set_position_gain_range()).
        if self._position_kp_range is not None:
            kp = self.np_random.uniform(*self._position_kp_range)
            kd = self.np_random.uniform(*self._position_kd_range)
            self._apply_position_gains(kp, kd)
            self.position_kp = kp
            self.position_kd = kd

        mujoco.mj_forward(self.model, self.data)

        # control_mode='torque_belt' only: seed this episode's belt-servo reference (per leg) at the starting pose
        if self.control_mode == 'torque_belt':
            self._belt_target_abs_calf = self.data.ten_length[self.calf_tendon_ids].copy()

        # See NO_PROGRESS_GRACE_S's comment / _no_forward_progress()
        self._episode_start_y = self.data.xpos[self.torso_body_id][1]
        # See WALK_HEADING_DEVIATION_PENALTY_WEIGHT's comment -- same
        # timing reasoning as self._episode_start_y above.
        self._episode_start_yaw = self._torso_yaw_rad()

        # Fill the WHOLE calf-hinge activity window with this episode's actual reset-time reading (not zeros)
        self._calf_hinge_window[:] = self.data.qpos[
            self.motor_qpos_adr[self.calf_idx]]
        self._calf_hinge_window_idx = 0

        # Same reset-time fill, thigh instead of calf
        self._thigh_hinge_window[:] = self.data.qpos[
            self.motor_qpos_adr[SYMMETRIC_THIGH_IDX]]
        self._thigh_hinge_window_idx = 0

        # Populate initial history (copy the first obs to all history slots)
        initial_obs = self._get_obs()
        for i in range(self.obs_history_len):
            self._obs_history[i * self.single_obs_dim : (i + 1) * self.single_obs_dim] = initial_obs

        return self._obs_history.copy(), {}

    def _randomize_ground(self):
        friction = self.np_random.uniform(*FLOOR_FRICTION_RANGE)
        self.model.geom_friction[self.floor_geom_id] = [friction, friction * 0.1, friction * 0.1]

    def _apply_position_gains(self, kp, kd):
        """Writes kp/kd directly into the loaded model's <position> actuator gain/bias params."""

        self.model.actuator_gainprm[:, 0] = kp
        self.model.actuator_biasprm[:, 1] = -kp
        self.model.actuator_biasprm[:, 2] = -kd

    def _apply_joint_stiffness(self, value):
        """Writes a passive restoring-spring stiffness directly into the loaded model's per-THIGH-joint jnt_stiffness (MuJoCo's ..."""

        self.model.jnt_stiffness[self._thigh_joint_ids] = value

    def set_position_gain_range(self, kp_range, kd_range):
        """Updates the (low, high) bounds reset() samples position_kp/ position_kd from on the NEXT episode."""

        self._position_kp_range = kp_range
        self._position_kd_range = kd_range

    def set_home_start_prob(self, prob):
        """Updates the probability reset() uses to pick 'home' over 'standing' when walk_start_pose='random', on the NEXT episode."""

        self._home_start_prob = prob

    def set_max_slew_deg_per_s(self, value):
        """Updates the per-step slew clamp step() applies to position-mode actions, effective IMMEDIATELY on the very next step(..."""

        self._max_slew_deg_per_s = value

    def set_walk_forward_progress_target_m_s(self, value):
        """Updates the WALK task's forward-speed reward target, effective IMMEDIATELY on the very next reward computation."""

        self._walk_forward_progress_target_m_s = value

    def step(self, action):
        action = np.clip(action, self.action_space.low, self.action_space.high)
        if self.control_mode == 'torque':
            # Direct torque control see control_mode's comment in __init__): action IS the <motor> actuator's ctrl value, already clipped to ctrlrange above.
            self.data.ctrl[:] = action - TORQUE_KD_GAIN * self.data.qvel[self.motor_dof_adr]
        elif self.control_mode == 'torque_belt':
            # Same base torque + damping as 'torque' above (thighs completely untouched), PLUS an automatic, NON-learned belt-compensation PD servo added to the calf motors only
            ctrl = action - TORQUE_KD_GAIN * self.data.qvel[self.motor_dof_adr]
            abs_calf = self.data.ten_length[self.calf_tendon_ids]
            abs_calf_vel = self.data.ten_velocity[self.calf_tendon_ids]
            # ADAPTIVE target _WALK's comment)
            self._belt_target_abs_calf += self._belt_target_adapt_rate * (abs_calf - self._belt_target_abs_calf)
            belt_pd = (BELT_SERVO_KP * (self._belt_target_abs_calf - abs_calf)
                       + BELT_SERVO_KD * (0.0 - abs_calf_vel))
            ctrl[self.calf_idx] += belt_pd
            # REACTION CANCELLATION @16M): the <fixed> tendon combines BOTH the calf and thigh joints (coef=[1, -calf_belt_sign], see generate_dog_mjcf.py), so MuJoCo distributes belt_pd back to the THIGH too, not just the calf
            ctrl[self.calf_thigh_idx] += self.calf_belt_sign * belt_pd
            self.data.ctrl[:] = ctrl
        else:
            if self.task == 'walk':
                # RESIDUAL -> ABSOLUTE conversion (see WALK_ACTION_RESIDUAL_RANGE_RAD's comment)
                if self._episode_start_pose == 'home':
                    elapsed_s = self._step_count * self.model.opt.timestep
                    alpha = np.clip(elapsed_s / HOME_RISE_INTERPOLATION_DURATION_S, 0.0, 1.0)
                    alpha_eased = (1.0 - np.cos(np.pi * alpha)) / 2.0
                    walk_baseline = alpha_eased * self._walk_default_action_rad
                else:
                    walk_baseline = self._walk_default_action_rad
                action = walk_baseline + action
            # Rate-limit how far any single motor's target can move per step.
            max_delta_rad = np.radians(self._max_slew_deg_per_s) * self.model.opt.timestep
            action = np.clip(action, self.prev_action - max_delta_rad, self.prev_action + max_delta_rad)

            # Belt/pulley compensation (see calf_idx's comment in __init__, including the sign note): action[calf] is an ABSOLUTE angle; dog.mjcf.xml's calf actuator servos a thigh-RELATIVE hinge, so ADD the thigh's current angle before writing ctrl.
            ctrl = action.copy()
            ctrl[self.calf_idx] = action[self.calf_idx] + self.calf_belt_sign * self.data.qpos[self.calf_thigh_qpos_adr]
            self.data.ctrl[:] = ctrl

        # Push perturbation, STAND + WALK (see PUSH_PROB_PER_STEP's comment)
        if self.task in ('stand', 'walk') and self.domain_randomization:
            dt = self.model.opt.timestep
            if self._push_remaining_s <= 0.0 and self.np_random.uniform() < PUSH_PROB_PER_STEP:
                angle = self.np_random.uniform(0.0, 2 * np.pi)
                magnitude = self.np_random.uniform(*PUSH_FORCE_RANGE_N)
                self._push_force = np.array(
                    [magnitude * np.cos(angle), magnitude * np.sin(angle), 0.0])
                # Direct roll/pitch torque RANGE_NM's comment)
                torque_angle = self.np_random.uniform(0.0, 2 * np.pi)
                torque_magnitude = self.np_random.uniform(*PUSH_TORQUE_RANGE_NM)
                self._push_torque = np.array(
                    [torque_magnitude * np.cos(torque_angle),
                     torque_magnitude * np.sin(torque_angle), 0.0])
                self._push_remaining_s = PUSH_DURATION_S
            if self._push_remaining_s > 0.0:
                self.data.xfrc_applied[self.torso_body_id, 0:3] = self._push_force
                self.data.xfrc_applied[self.torso_body_id, 3:6] = self._push_torque
                self._push_remaining_s -= dt
            else:
                self.data.xfrc_applied[self.torso_body_id, :] = 0.0
        elif self.data.xfrc_applied[self.torso_body_id].any():
            # Task/mode switched or domain_randomization turned off mid-episode (shouldn't normally happen, but don't leave a stale push force applied forever if it does).
            self.data.xfrc_applied[self.torso_body_id, :] = 0.0

        if self.render_mode == 'human':
            self._ensure_viewer()
            # Space bar toggles self._paused via _on_key.
            while self._paused and self.renderer.is_running():
                self.renderer.sync()
                time.sleep(0.02)

        mujoco.mj_step(self.model, self.data)
        self._step_count += 1
        # MUST update before _compute_reward()
        self._update_leg_phase_time()
        self._update_high_pitch_time()
        # MUST also update before _compute_reward() during implementation
        self._update_standing_hold_time()
        # MUST also update before _compute_reward()
        self._update_swing_duty_cycle()
        # MUST also update before _compute_reward()
        self._update_calf_hinge_activity()
        # MUST also update before _compute_reward()
        self._update_thigh_hinge_activity()
        # MUST also update before _compute_reward()
        self._update_calf_margin_time()
        # MUST also update before _compute_reward()
        self._update_calf_stance_straight_time()
        # MUST also update before _compute_reward()
        self._update_calf_stance_side_time()
        # MUST also update before _compute_reward()
        self._update_calf_thigh_tracking_time()

        reward = self._compute_reward(action)

        self.prev_action = action.astype(np.float32)

        current_obs = self._get_obs()
        self._obs_history[:-self.single_obs_dim] = self._obs_history[self.single_obs_dim:]
        self._obs_history[-self.single_obs_dim:] = current_obs
        obs = self._obs_history.copy()
        
        # MUST update before checking _knee_walking_too_long() -- see that
        # method's docstring.
        self._update_nontip_contact_time()
        # MUST update before checking _not_all_feet_grounded() -- same
        # reasoning, see _update_airborne_time()'s docstring.
        self._update_airborne_time()
        # The three checks after _knee_walking_too_long() are additional WALK-only early terminations
        if self.task == 'walk' and self.gait_style == 'bound':
            fell_over = self._knee_walking_too_long()
            terminated = fell_over
        else:
            fell_over = (self._is_fallen() or self._knee_walking_too_long()
                         or self._leg_stuck_too_long() or self._pitch_diverging_too_long()
                         or self._not_all_feet_grounded())
            terminated = fell_over or self._no_forward_progress()
        truncated = self._step_count >= MAX_EPISODE_STEPS

        if self.task == 'walk' and fell_over:
            reward += WALK_FALL_TERMINAL_PENALTY

        if self.render_mode == 'human':
            self.render()

        return obs, reward, terminated, truncated, {}

    def _get_obs(self):
        # Belt/pulley compensation (see calf_idx's comment in __init__): convert the calf hinge's raw, thigh-relative qpos/qvel into the ABSOLUTE angle/rate the real motor's own encoder would report, so the policy's observation matches actuator/dog_deploy's read_motor_positions on real hardware with no further change needed there.
        motor_qpos = self.data.qpos[self.motor_qpos_adr].copy()
        motor_qvel = self.data.qvel[self.motor_dof_adr].copy()
        motor_qpos[self.calf_idx] -= self.calf_belt_sign * self.data.qpos[self.calf_thigh_qpos_adr]
        motor_qvel[self.calf_idx] -= self.calf_belt_sign * self.data.qvel[self.calf_thigh_dof_adr]
        sensordata = self.data.sensordata

        # SENSOR NOISE : real-hardware deployment of a "converged"-looking stand policy showed persistent chatter at a settled stand pose, traced directly to the raw policy action itself being unstable at steady state (see action_rate_penalty's comment in _common_penalties())
        if self.domain_randomization:
            motor_qpos = motor_qpos + self.np_random.normal(
                0.0, MOTOR_POS_NOISE_STD_RAD, size=NUM_MOTORS)
            motor_qvel = motor_qvel + self.np_random.normal(
                0.0, MOTOR_VEL_NOISE_STD_RAD_S, size=NUM_MOTORS)
            sensordata = sensordata.copy()
            sensordata[0:3] += self.np_random.normal(0.0, ACCEL_NOISE_STD_M_S2, size=3)
            sensordata[3:6] += self.np_random.normal(0.0, GYRO_NOISE_STD_RAD_S, size=3)

        return np.concatenate([
            motor_qpos,
            motor_qvel,
            sensordata,
            self.prev_action,
        ]).astype(np.float32)

    def _torso_height(self):
        return self.data.xpos[self.torso_body_id][2]

    def _climb_progress(self):
        """0 at SIT_HEIGHT_M ('home' start height), 1 at _walk_target_height_m."""

        adjusted_height = self._torso_height() - self._rise_progress_height_offset
        return np.clip(
            (adjusted_height - SIT_HEIGHT_M) / (self._walk_target_height_m - SIT_HEIGHT_M),
            0.0, 1.0)

    def _get_rise_progress(self):
        """0 at SIT_HEIGHT_M ('home' start height), 1 at the task's own target standing height."""

        if self.task == 'walk':
            return self._climb_progress()
        adjusted_height = self._torso_height() - self._rise_progress_height_offset
        return np.clip(
            (adjusted_height - SIT_HEIGHT_M) / (STAND_HEIGHT_M - SIT_HEIGHT_M), 0.0, 1.0)

    def _stand_progress(self):
        """0 at SIT_HEIGHT_M, 1 at FULL STAND_HEIGHT_M."""

        return np.clip(
            (self._torso_height() - SIT_HEIGHT_M) / (STAND_HEIGHT_M - SIT_HEIGHT_M),
            0.0, 1.0)

    def _torso_up_z(self):
        """World-frame z-component of the torso's local up axis: 1.0 = perfectly upright, drops towards 0 as the robot tips over."""

        xmat = self.data.xmat[self.torso_body_id].reshape(3, 3)
        return xmat[2, 2]

    def _torso_pitch_rad(self):
        """Forward/backward tilt (radians): 0 = level, positive = nose- down (pitching forward)."""

        xmat = self.data.xmat[self.torso_body_id].reshape(3, 3)
        return np.arcsin(np.clip(-xmat[2, 1], -1.0, 1.0))

    def _torso_roll_rad(self):
        """Side-to-side tilt (radians): 0 = level, positive = right side down."""

        xmat = self.data.xmat[self.torso_body_id].reshape(3, 3)
        return np.arcsin(np.clip(xmat[2, 0], -1.0, 1.0))

    def _torso_yaw_rad(self):
        """Heading angle (radians) about the world z-axis: 0 = facing the model's native forward (+y) direction, matching atan2'..."""

        xmat = self.data.xmat[self.torso_body_id].reshape(3, 3)
        return np.arctan2(xmat[0, 1], xmat[1, 1])

    def _body_frame_xy_velocity(self):
        """(forward, lateral) components of the free joint's world-frame xy velocity (qvel[0:2]), projected onto the torso's OWN..."""

        xmat = self.data.xmat[self.torso_body_id].reshape(3, 3)
        forward_axis_xy = xmat[0:2, 1]
        right_axis_xy = xmat[0:2, 0]
        world_vel_xy = self.data.qvel[0:2]
        forward_vel = float(np.dot(world_vel_xy, forward_axis_xy))
        lateral_vel = float(np.dot(world_vel_xy, right_axis_xy))
        return forward_vel, lateral_vel

    def _num_feet_grounded(self):
        """How many of the 4 calf capsules are in actual contact with the floor geom right now (0-4)."""

        grounded = set()
        for i in range(self.data.ncon):
            c = self.data.contact[i]
            if c.geom1 == self.floor_geom_id and c.geom2 in self.calf_geom_ids:
                grounded.add(c.geom2)
            elif c.geom2 == self.floor_geom_id and c.geom1 in self.calf_geom_ids:
                grounded.add(c.geom1)
        return len(grounded)

    def _foot_contact_per_leg(self):
        """[bool x4] (leg_a, leg_b, leg_c, leg_d order, matching calf_geom_ids/foot_site_ids): True if that leg has ANY floor co..."""

        return [state != 'air' for state in self._foot_contact_state_per_leg()]

    def _trot_symmetry_reward(self):
        """Rewards a diagonal-pair TROT contact pattern."""

        if np.any(self._leg_phase_time > MAX_LEG_PHASE_S):
            return -1.0
        a, b, c, d = self._foot_contact_per_leg()
        pair_ad_synced = 1.0 if a == d else -1.0
        pair_bc_synced = 1.0 if b == c else -1.0
        pairs_offset = 1.0 if a != b else -1.0
        return (pair_ad_synced + pair_bc_synced + pairs_offset) / 3.0

    def _bound_symmetry_reward(self):
        """Rewards a front/back-pair BOUND contact pattern."""

        if np.any(self._leg_phase_time > MAX_LEG_PHASE_S):
            return -1.0
        a_z, b_z, c_z, d_z = (
            max(self.data.site_xpos[site_id][2], 0.0) for site_id in self.foot_site_ids)
        # Normalize by FOOT_CLEARANCE_TARGET_M (the same "full swing" calibration _foot_clearance_reward() already uses) so this stays on a comparable [~0, ~1] scale regardless of the robot's absolute size
        a_air, b_air, c_air, d_air = (
            z / FOOT_CLEARANCE_TARGET_M for z in (a_z, b_z, c_z, d_z))
        pair_ab_synced = 1.0 - 2.0 * abs(a_air - b_air)
        pair_cd_synced = 1.0 - 2.0 * abs(c_air - d_air)
        pairs_offset = 2.0 * abs((a_air + b_air) / 2.0 - (c_air + d_air) / 2.0) - 1.0
        return float(np.clip((pair_ab_synced + pair_cd_synced + pairs_offset) / 3.0, -1.0, 1.0))

    def _foot_clearance_reward(self, leg_indices=None, target_m=None):
        """Rewards a SWINGING (non-contacting) foot for actually being elevated, not dragged along the ground."""

        contacted = self._foot_contact_per_leg()
        swinging = [not c for c in contacted]
        indices = leg_indices if leg_indices is not None else range(len(self.foot_site_ids))
        swinging_indices = [i for i in indices if swinging[i]]
        if not swinging_indices:
            return 0.0  # no (selected) leg is swinging right now -- neutral, NOT rewarded (see bug note above)
        total = 0.0
        # target_m MORE than the current split fix gives" investigation): optional override of FOOT_CLEARANCE_TARGET_M, for back_clearance_reward's own higher BACK_FOOT_CLEARANCE_TARGET_M (real-hardware back legs still drag somewhat even with the front/back split's equal-weight fix
        target = target_m if target_m is not None else FOOT_CLEARANCE_TARGET_M
        sigma = target / 2
        for i in swinging_indices:
            site_id = self.foot_site_ids[i]
            foot_z = max(self.data.site_xpos[site_id][2], 0.0)
            total += float(np.exp(-((foot_z - target) ** 2) / (2 * sigma ** 2)))
        return total / len(swinging_indices)

    def _calf_swing_motion_reward(self):
        """Rewards a SWINGING leg's calf (knee) for actively moving, not staying near-fixed while the thigh does all the work of..."""

        contacted = self._foot_contact_per_leg()
        swinging = [not c for c in contacted]
        if not any(swinging):
            return 0.0
        calf_qvel = self.data.qvel[self.motor_dof_adr[self.calf_idx]]
        total = sum(calf_qvel[i] ** 2 for i in range(4) if swinging[i])
        return min(total / sum(swinging), CALF_SWING_REWARD_CAP)

    def _foot_horizontal_speed_sq(self, leg_idx):
        """Squared horizontal (world x/y) speed of a leg's foot site right now, via MuJoCo's site-Jacobian velocity (mj_objectVe..."""

        site_id = self.foot_site_ids[leg_idx]
        vel = np.zeros(6)  # [angular(3), linear(3)]
        mujoco.mj_objectVelocity(self.model, self.data, mujoco.mjtObj.mjOBJ_SITE, site_id, vel, 0)
        return float(np.dot(vel[3:5], vel[3:5]))

    def _foot_slip_penalty(self):
        """Penalizes a foot's horizontal velocity WHILE IN CONTACT with the ground."""

        contacted = self._foot_contact_per_leg()
        total = 0.0
        for i in range(len(self.foot_site_ids)):
            if contacted[i]:
                total += self._foot_horizontal_speed_sq(i)
        return -total

    def _touchdown_velocity_penalty(self):
        """Penalizes a foot's vertical (world z) speed at the exact moment of landing (contact resuming after a nonzero air time)."""

        contacted = self._foot_contact_per_leg()
        total = 0.0
        for i in range(4):
            if contacted[i] and self._feet_air_time[i] > 0.0:
                site_id = self.foot_site_ids[i]
                vel = np.zeros(6)  # [angular(3), linear(3)]
                mujoco.mj_objectVelocity(self.model, self.data, mujoco.mjtObj.mjOBJ_SITE, site_id, vel, 0)
                total += vel[5] ** 2  # vertical (world z) linear speed squared
        return -total

    def _feet_air_time_reward(self):
        """Rewards a leg for swinging roughly FEET_AIR_TIME_TARGET_S before landing again."""

        contacted = self._foot_contact_per_leg()
        dt = self.model.opt.timestep
        reward = 0.0
        for i in range(4):
            if contacted[i]:
                if self._feet_air_time[i] > 0.0:
                    reward += self._feet_air_time[i] - FEET_AIR_TIME_TARGET_S
                self._feet_air_time[i] = 0.0
                self._feet_stance_time[i] += dt
                if self._feet_stance_time[i] > FEET_STANCE_TIME_MAX_S:
                    reward -= (self._feet_stance_time[i] - FEET_STANCE_TIME_MAX_S)
            else:
                self._feet_air_time[i] += dt
                self._feet_stance_time[i] = 0.0
                if self._feet_air_time[i] > FEET_AIR_TIME_MAX_S:
                    reward -= (self._feet_air_time[i] - FEET_AIR_TIME_MAX_S)
        return reward

    def _foot_contact_state_per_leg(self):
        """['air'|'tip'|'nontip'] x4, in (leg_a, leg_b, leg_c, leg_d) order."""

        state = ['air'] * len(self.calf_geom_ids)
        for i in range(self.data.ncon):
            c = self.data.contact[i]
            for near, far in ((c.geom1, c.geom2), (c.geom2, c.geom1)):
                if near != self.floor_geom_id:
                    continue
                if far in self.thigh_geom_ids:
                    state[self.thigh_geom_ids.index(far)] = 'nontip'
                elif far in self.calf_geom_ids:
                    leg_idx = self.calf_geom_ids.index(far)
                    if state[leg_idx] == 'nontip':
                        continue  # thigh already flagged this leg -- don't let a
                                  # same-step calf-tip contact downgrade it back
                    foot_pos = self.data.site_xpos[self.foot_site_ids[leg_idx]]
                    is_tip = np.linalg.norm(np.array(c.pos) - foot_pos) < FOOT_CONTACT_RADIUS_M
                    state[leg_idx] = 'tip' if is_tip else 'nontip'
        return state

    def _foot_tip_contact_count(self):
        """(num_tip, num_non_tip): aggregate counts derived from _foot_contact_state_per_leg() (the single source of truth for p..."""

        state = self._foot_contact_state_per_leg()
        return state.count('tip'), state.count('nontip')

    def _foot_placement_terms(self):
        """(tip_reward, non_tip_penalty) shared by both tasks: tip_reward in [0, 1] is the fraction of the 4 feet grounded at th..."""

        num_tip, num_non_tip = self._foot_tip_contact_count()
        return num_tip / 4.0, -1.0 * num_non_tip

    def _is_fallen(self):
        if self._torso_height() < FALL_HEIGHT_M:
            return True
        max_tilt = WALK_MAX_TILT_RAD if self.task == 'walk' else MAX_TILT_RAD
        if self._torso_up_z() < np.cos(max_tilt):
            return True
        return False

    def _update_nontip_contact_time(self):
        """Advances self._non_tip_contact_time per leg"""

        state = self._foot_contact_state_per_leg()
        dt = self.model.opt.timestep
        for i in range(4):
            if state[i] == 'nontip':
                self._non_tip_contact_time[i] += dt
            else:
                self._non_tip_contact_time[i] = 0.0

        # BOUND ONLY
        if self.gait_style == 'bound':
            torso_touching = False
            for i in range(self.data.ncon):
                c = self.data.contact[i]
                if ((c.geom1 == self.torso_geom_id and c.geom2 == self.floor_geom_id)
                        or (c.geom2 == self.torso_geom_id and c.geom1 == self.floor_geom_id)):
                    torso_touching = True
                    break
            if torso_touching:
                self._torso_contact_time += dt
            else:
                self._torso_contact_time = 0.0

    def _update_airborne_time(self):
        """Advances self._airborne_time per leg"""

        contacted = self._foot_contact_per_leg()
        dt = self.model.opt.timestep
        for i in range(4):
            if not contacted[i]:
                self._airborne_time[i] += dt
            else:
                self._airborne_time[i] = 0.0

    def _update_standing_hold_time(self):
        """Advances self._standing_hold_time"""

        dt = self.model.opt.timestep
        if self._stand_progress() >= WALK_STAND_HOLD_THRESHOLD:
            self._standing_hold_time += dt
            self._standing_hold_dip_time = 0.0
        else:
            self._standing_hold_dip_time += dt
            if self._standing_hold_dip_time > WALK_STAND_HOLD_DIP_GRACE_S:
                self._standing_hold_time = 0.0

    def _update_leg_phase_time(self):
        """Advances self._leg_phase_time per leg"""

        contacted = np.array(self._foot_contact_per_leg())
        dt = self.model.opt.timestep
        if self.walk_start_pose == 'random' and self._standing_hold_time < WALK_STAND_HOLD_S:
            self._leg_phase_time[:] = 0.0
            self._prev_leg_contact = contacted
            return
        changed = contacted != self._prev_leg_contact
        self._leg_phase_time[changed] = 0.0
        self._leg_phase_time[~changed] += dt
        self._prev_leg_contact = contacted

    def _update_swing_duty_cycle(self):
        """Advances self._contact_duty_cycle"""

        contacted = np.array(self._foot_contact_per_leg(), dtype=np.float64)
        self._contact_duty_cycle = (
            SWING_FAIRNESS_EMA_ALPHA * contacted
            + (1.0 - SWING_FAIRNESS_EMA_ALPHA) * self._contact_duty_cycle)

    def _update_calf_hinge_activity(self):
        """Writes this tick's RAW calf hinge angle (rad, the actual physical knee joint."""

        self._calf_hinge_window[self._calf_hinge_window_idx] = (
            self.data.qpos[self.motor_qpos_adr[self.calf_idx]])
        self._calf_hinge_window_idx = (
            (self._calf_hinge_window_idx + 1) % CALF_ACTIVITY_WINDOW_TICKS)

    def _update_thigh_hinge_activity(self):
        """Same true-sliding-window pattern as _update_calf_hinge_ activity() above, RAW thigh qpos instead of calf."""

        self._thigh_hinge_window[self._thigh_hinge_window_idx] = (
            self.data.qpos[self.motor_qpos_adr[SYMMETRIC_THIGH_IDX]])
        self._thigh_hinge_window_idx = (
            (self._thigh_hinge_window_idx + 1) % CALF_ACTIVITY_WINDOW_TICKS)

    def _update_calf_margin_time(self):
        """Advances self._calf_margin_time per calf joint"""

        calf_qpos = self.data.qpos[self.motor_qpos_adr[self.calf_idx]]
        margin = np.minimum(
            calf_qpos - self._calf_joint_range_lo,
            self._calf_joint_range_hi - calf_qpos)
        dt = self.model.opt.timestep
        in_margin_band = margin < CALF_JOINT_MARGIN_FLOOR_RAD
        self._calf_margin_time = np.where(
            in_margin_band, self._calf_margin_time + dt, 0.0)

    def _update_calf_stance_straight_time(self):
        """Advances self._calf_stance_straight_time per leg"""

        calf_qpos = self.data.qpos[self.motor_qpos_adr[self.calf_idx]]
        distance_from_straight = np.abs(calf_qpos - self._calf_straight_center_rad)
        in_straight_zone = distance_from_straight < STANCE_STRAIGHT_ZONE_RAD
        state = self._foot_contact_state_per_leg()
        in_stance = np.array([s == 'tip' for s in state])
        dt = self.model.opt.timestep
        self._calf_stance_straight_time = np.where(
            in_straight_zone & in_stance, self._calf_stance_straight_time + dt, 0.0)

    def _update_calf_stance_side_time(self):
        """Advances self._calf_wrong_side_time per leg"""

        calf_qpos = self.data.qpos[self.motor_qpos_adr[self.calf_idx]]
        side = np.sign(calf_qpos - self._calf_straight_center_rad)
        distance_from_straight = np.abs(calf_qpos - self._calf_straight_center_rad)
        state = self._foot_contact_state_per_leg()
        in_stance = np.array([s == 'tip' for s in state])
        dt = self.model.opt.timestep

        entering_stance = in_stance & ~self._prev_in_stance
        self._calf_stance_entry_side = np.where(
            entering_stance, side, self._calf_stance_entry_side)

        on_wrong_side = (
            in_stance & (side != 0.0) & (self._calf_stance_entry_side != 0.0)
            & (side != self._calf_stance_entry_side)
            & (distance_from_straight > STANCE_STRAIGHT_ZONE_RAD))
        self._calf_wrong_side_time = np.where(
            on_wrong_side, self._calf_wrong_side_time + dt, 0.0)

        self._prev_in_stance = in_stance

    def _update_calf_thigh_tracking_time(self):
        """Advances self._calf_poor_tracking_time per leg"""

        calf_qvel = self.data.qvel[self.motor_dof_adr[self.calf_idx]]
        thigh_qvel = self.data.qvel[self.calf_thigh_dof_adr]
        state = self._foot_contact_state_per_leg()
        in_stance = np.array([s == 'tip' for s in state])
        dt = self.model.opt.timestep

        thigh_moving = np.abs(thigh_qvel) > CALF_THIGH_TRACKING_THIGH_QVEL_FLOOR_RAD_S
        wrong_direction = np.sign(calf_qvel) != np.sign(thigh_qvel)
        too_slow = np.abs(calf_qvel) < CALF_THIGH_TRACKING_MIN_CALF_FRACTION * np.abs(thigh_qvel)
        poor_tracking = in_stance & thigh_moving & (wrong_direction | too_slow)
        self._calf_poor_tracking_time = np.where(
            poor_tracking, self._calf_poor_tracking_time + dt, 0.0)

    def _update_high_pitch_time(self):
        """Advances self._high_pitch_time"""

        dt = self.model.opt.timestep
        pitch_rad = self._torso_pitch_rad()
        if pitch_rad > PITCH_TERMINATION_FORWARD_RAD or pitch_rad < PITCH_TERMINATION_BACKWARD_RAD:
            self._high_pitch_time += dt
        else:
            self._high_pitch_time = 0.0

    def _leg_stuck_too_long(self):
        """WALK only: True if any leg has held the SAME contact phase (grounded or swinging, self._leg_phase_time) for longer th..."""

        if self.task != 'walk':
            return False
        return bool(np.any(self._leg_phase_time > LEG_PHASE_TERMINATION_S))

    def _pitch_diverging_too_long(self):
        """WALK only: True if torso pitch has stayed outside [PITCH_TERMINATION_BACKWARD_RAD, PITCH_TERMINATION_FORWARD_RAD] con..."""

        if self.task != 'walk':
            return False
        return self._high_pitch_time > PITCH_TERMINATION_DURATION_S

    def _no_forward_progress(self):
        """WALK only: True if, past an initial NO_PROGRESS_GRACE_S grace period, this episode still hasn't moved NO_PROGRESS_MIN..."""

        if self.task != 'walk':
            return False
        elapsed_s = self._step_count * self.model.opt.timestep
        if elapsed_s < NO_PROGRESS_GRACE_S:
            return False
        forward_displacement = self.data.xpos[self.torso_body_id][1] - self._episode_start_y
        return forward_displacement < NO_PROGRESS_MIN_DISTANCE_M

    def _knee_walking_too_long(self):
        """True if any leg has been in continuous non-tip (knee/thigh/shin) contact for longer than NONTIP_TERMINATION_S."""

        if not NONTIP_TERMINATION_ENABLED:
            return False
        adjusted_height = self._torso_height() - self._rise_progress_height_offset
        if adjusted_height < NONTIP_TERMINATION_MIN_RISE_HEIGHT_M:
            return False
        threshold = (NONTIP_TERMINATION_S_STANDING
                     if getattr(self, '_episode_start_pose', None) == 'standing'
                     else NONTIP_TERMINATION_S)
        if bool(np.any(self._non_tip_contact_time > threshold)):
            return True
        # BOUND ONLY
        if self.gait_style == 'bound' and self._torso_contact_time > NONTIP_TERMINATION_S_BOUND:
            return True
        return False

    def _not_all_feet_grounded(self):
        """STAND only: True if any leg has been fully airborne (no floor contact at all."""

        if self.task != 'stand':
            return False
        return bool(np.any(self._airborne_time > STAND_AIRBORNE_TERMINATION_S))

    def _common_penalties(self, action):
        """Terms both tasks share: IMU-based shock penalty + effort + a per-step survival bonus."""

        # sensordata layout matches the <sensor> block in dog.mjcf.xml:
        # [0:3] accelerometer, [3:6] gyro.
        linear_accel = self.data.sensordata[0:3]
        gravity_m_s2 = 9.81
        accel_shock_penalty = -0.01 * (np.linalg.norm(linear_accel) - gravity_m_s2) ** 2

        # SCALE BUG FIXED against position mode's action (radians, ~4-8 rad span per motor).
        if self.control_mode in ('torque', 'torque_belt'):
            normalized_action = action / self.action_space.high
            effort_penalty = -0.001 * float(np.dot(normalized_action, normalized_action))
        else:
            effort_penalty = -0.001 * float(np.dot(action, action))

        survival_bonus = 0.05

        return accel_shock_penalty + effort_penalty + survival_bonus

    def _angular_vel_penalty(self, weight):
        """weight * dot(angular_vel, angular_vel)."""

        angular_vel = self.data.sensordata[3:6]
        return weight * float(np.dot(angular_vel, angular_vel))

    def _action_rate_penalty(self, action, weight):
        """weight * sum((action - prev_action)**2)."""

        delta = action - self.prev_action
        if self.control_mode in ('torque', 'torque_belt'):
            delta = delta / self.action_space.high
        return weight * float(np.sum(delta ** 2))

    def _compute_reward(self, action):
        if self.task == 'stand':
            return self._compute_reward_stand(action)
        return self._compute_reward_walk(action)

    def _compute_reward_stand(self, action):
        # UNCAPPED height reward robot stand to its maximum height")
        height_reward = self._torso_height() - SIT_HEIGHT_M
        height_error = abs(self._torso_height() - STAND_HEIGHT_M)
        # Bonus on top of the continuous shaping term once within tolerance
        height_bonus = 0.2 if height_error < STAND_HEIGHT_TOLERANCE_M else 0.0

        # Gate uprightness by standing progress (0 at sitting height, 1 at the target) instead of paying it out unconditionally
        height_progress = self._get_rise_progress()
        upright_reward = self._torso_up_z() * height_progress  # 1.0 = perfectly level AND at height

        motor_qpos = self.data.qpos[self.motor_qpos_adr]
        # THIGH_SYMMETRY_SIGN/CALF_SYMMETRY_SIGN correct for the left/right (thigh) and front/back (calf) mirrored joint axes before comparing
        thigh_spread = np.var(motor_qpos[SYMMETRIC_THIGH_IDX] * THIGH_SYMMETRY_SIGN)
        calf_spread = np.var(motor_qpos[SYMMETRIC_CALF_IDX] * CALF_SYMMETRY_SIGN)
        symmetry_penalty = -1.0 * (thigh_spread + calf_spread)

        # Standing still means staying in place, not just staying up --
        # qvel[0:2] is the free joint's world-frame x/y linear velocity.
        drift_penalty = -0.1 * float(np.dot(self.data.qvel[0:2], self.data.qvel[0:2]))

        # All 4 feet should be on the ground AT THE FOOT TIP once actually standing (user observed a trained policy reaching the target height on only 3 legs, and separately a walk policy standing on its knees instead of its feet
        tip_reward, non_tip_penalty = self._foot_placement_terms()
        # AIRBORNE PENALTY ADDED came back" investigation
        num_airborne_legs = 4 - sum(self._foot_contact_per_leg())
        grounded_reward = (tip_reward + non_tip_penalty - num_airborne_legs) * height_progress

        # Gated by height_progress, same pattern as upright_reward/ grounded_reward above
        action_rate_weight = (
            ACTION_RATE_PENALTY_WEIGHT_RISING
            + (ACTION_RATE_PENALTY_WEIGHT_STANDING - ACTION_RATE_PENALTY_WEIGHT_RISING) * height_progress
        )
        action_rate_penalty = self._action_rate_penalty(action, action_rate_weight)
        angular_vel_penalty = self._angular_vel_penalty(STAND_ANGULAR_VEL_PENALTY_WEIGHT)

        # NEW : direct penalty on JOINT velocity (qvel), distinct from angular_vel_ penalty above (that's the TORSO's angular velocity from the IMU/gyro, torso wobble
        motor_qvel = self.data.qvel[self.motor_dof_adr]
        joint_velocity_penalty = -float(np.dot(motor_qvel, motor_qvel))

        # action_rate_penalty/common_penalties ZEROED request, matching _compute_reward_walk()'s simple_rewards treatment)
        return (
            3.0 * height_reward
            + height_bonus
            + 2.0 * upright_reward
            + 1.5 * grounded_reward
            + symmetry_penalty
            + drift_penalty
            + 0.0 * action_rate_penalty
            + angular_vel_penalty
            + 0.01 * joint_velocity_penalty
            + 0.0 * self._common_penalties(action)
        )

    def _compute_reward_walk(self, action):
        # dog.mjcf.xml is still in the CAD's own native frame (+y=front, +x=right
        forward_velocity_reward, lateral_velocity = self._body_frame_xy_velocity()
        # Gated by forward progress (0 at zero/negative velocity, 1 at WALK_FORWARD_PROGRESS_TARGET_M_S+)
        forward_progress = np.clip(forward_velocity_reward / self._walk_forward_progress_target_m_s, 0.0, 1.0)
        # CAPPED the robot is not moving smoothly")
        if forward_velocity_reward > self._walk_forward_progress_target_m_s:
            overshoot = forward_velocity_reward - self._walk_forward_progress_target_m_s
            sigma = self._walk_forward_progress_target_m_s
            forward_velocity_reward = self._walk_forward_progress_target_m_s * np.exp(
                -(overshoot ** 2) / (2 * sigma ** 2))

        # PITCH-GATED : the additive pitch_penalty further below was measured too weak to counteract this term during an actual forward dive (only -0.164 weighted at 13.4deg pitch vs +0.750 here, on the same v10 checkpoint).
        if forward_velocity_reward > 0:
            pitch_gate = np.exp(
                -((self._torso_pitch_rad() - WALK_TARGET_PITCH_RAD) ** 2)
                / (2 * WALK_PITCH_GATE_SIGMA_RAD ** 2))
            forward_velocity_reward = forward_velocity_reward * pitch_gate

        # ROLL-GATED investigation
        if forward_velocity_reward > 0:
            roll_gate = np.exp(
                -(self._torso_roll_rad() ** 2) / (2 * WALK_ROLL_GATE_SIGMA_RAD ** 2))
            forward_velocity_reward = forward_velocity_reward * roll_gate

        # ===== STAND+WALK ONLY SECTION (walk_start_pose='random') ===== Everything in this block is scoped behind is_stand_and_walk, and ONLY affects walk_start_pose='random' episodes
        is_stand_and_walk = (self.walk_start_pose == 'random')
        climb_progress = self._climb_progress()

        # forward_velocity_reward CLIMB-GATED watched PPO_77000000_walk_position_obshistory_home_and_stand_v1 and found it "did not even finish standing up before moving forward"
        if is_stand_and_walk:
            climb_gate = np.clip(
                (climb_progress - WALK_CLIMB_GATE_THRESHOLD) / (1.0 - WALK_CLIMB_GATE_THRESHOLD),
                0.0, 1.0)
            hold_gate = 1.0 if self._standing_hold_time >= WALK_STAND_HOLD_S else 0.0
            forward_velocity_reward = forward_velocity_reward * climb_gate * hold_gate

        # NOT re-centered on WALK_TARGET_PITCH_RAD deferral
        upright_reward = self._torso_up_z() * forward_progress

        # climb_posture_reward that stands up from home AND walks" investigation, RE-SCOPED header comment): height_reward below is an ungated, dense pull toward standing height, but NOTHING rewards good POSTURE (upright, level) while still below that height, since upright_reward above is gated by forward_progress (~0 during the climb, no forward velocity yet
        climb_posture_reward = (
            self._torso_up_z() * (1.0 - climb_progress) if is_stand_and_walk else 0.0)
        # ===== END STAND+WALK ONLY SECTION ===== See _trot_symmetry_reward()'s docstring
        leg_stuck = bool(np.any(self._leg_phase_time > MAX_LEG_PHASE_S))
        trot_symmetry_reward = (
            self._trot_symmetry_reward() if leg_stuck
            else self._trot_symmetry_reward() * forward_progress)
        # gait_symmetry_reward/gait_symmetry_weight gait_style/WALK_BOUND_SYMMETRY_WEIGHT's own comments)
        if self.gait_style == 'bound':
            bound_symmetry_reward = (
                self._bound_symmetry_reward() if leg_stuck
                else self._bound_symmetry_reward() * forward_progress)
            bound_symmetry_gate = np.clip(
                (forward_progress - WALK_BOUND_SYMMETRY_GATE_START)
                / (WALK_BOUND_SYMMETRY_GATE_FULL - WALK_BOUND_SYMMETRY_GATE_START),
                0.0, 1.0)
            gait_symmetry_reward = bound_symmetry_reward * bound_symmetry_gate
            gait_symmetry_weight = WALK_BOUND_SYMMETRY_WEIGHT
        else:
            gait_symmetry_reward = trot_symmetry_reward
            gait_symmetry_weight = 0.0 * WALK_TROT_SYMMETRY_WEIGHT
        # See WALK_SWING_FAIRNESS_WEIGHT's comment: replaces trot_symmetry_reward's dropped cross-leg role with a slower, duty-cycle-only signal that doesn't constrain per-tick timing.
        swing_fairness_gate = np.clip(
            (forward_progress - SWING_FAIRNESS_GATE_START)
            / (SWING_FAIRNESS_GATE_FULL - SWING_FAIRNESS_GATE_START),
            0.0, 1.0)
        swing_fairness_penalty = -float(np.sum(
            (self._contact_duty_cycle - SWING_FAIRNESS_TARGET_DUTY_CYCLE) ** 2)) * swing_fairness_gate
        # swing_amplitude_penalty
        thigh_deviation = np.abs(self.data.qpos[self.calf_thigh_qpos_adr])
        swing_amplitude_excess = np.clip(
            thigh_deviation - SWING_AMPLITUDE_MAX_DEVIATION_RAD, 0.0, None)
        swing_amplitude_penalty = -float(np.sum(swing_amplitude_excess ** 2))
        # calf_activity_penalty
        calf_hinge_range = (
            self._calf_hinge_window.max(axis=0) - self._calf_hinge_window.min(axis=0))
        calf_activity_deficit = np.clip(
            CALF_ACTIVITY_MIN_RANGE_RAD - calf_hinge_range, 0.0, None)
        calf_activity_penalty = -float(np.sum(calf_activity_deficit ** 2))
        # Targets self._walk_target_height_m (walk_height_fraction * full standing height, see __init__/WALK_HEIGHT_FRACTION's comment), not the stand task's full STAND_HEIGHT_M: a crouched walking height keeps the CoM lower and legs bent, discouraging both crawling/belly-flopping AND an overextended, easy-to-topple near-max-height stance.
        if is_stand_and_walk and self._standing_hold_time < WALK_STAND_HOLD_S:
            height_target = STAND_HEIGHT_M
        else:
            height_target = self._walk_target_height_m
        height_reward = -abs(self._torso_height() - height_target)

        # height_sag_penalty "revert EMA and implement the two reward-based fixes")
        height_deficit = max(0.0, height_target - self._torso_height())
        height_sag_penalty = -(height_deficit ** 2)

        # height_overshoot_penalty fraction 0.7 crouch experiment, same date)
        height_overshoot_penalty = -(
            max(0.0, self._torso_height() - height_target) ** 2)

        # Walk on the feet, not the knees/shins
        tip_reward, non_tip_penalty = self._foot_placement_terms()
        # GATED by forward_progress upright_reward and trot_symmetry_reward: measured directly on walk_policy_home_v2 (1M steps, --walk-start-pose home) at 1.10/step weighted (73% of its 1.5 ceiling) while forward_velocity_reward was only 0.066/step
        tip_reward = tip_reward * forward_progress

        # This alone wasn't enough
        front_clearance_reward = self._foot_clearance_reward(leg_indices=[0, 1]) * (0.5 + 0.5 * forward_progress)
        # back_clearance_reward is NEW
        back_clearance_gate = np.clip(
            (forward_progress - WALK_BACK_CLEARANCE_GATE_START)
            / (WALK_BACK_CLEARANCE_GATE_FULL - WALK_BACK_CLEARANCE_GATE_START),
            0.0, 1.0)
        back_clearance_reward = (self._foot_clearance_reward(leg_indices=[2, 3], target_m=BACK_FOOT_CLEARANCE_TARGET_M)
                                  * (0.5 + 0.5 * forward_progress) * back_clearance_gate)

        # NEW 's own docstring for the full "stiff-legged gait" diagnosis this is meant to fix).
        calf_swing_motion_reward = self._calf_swing_motion_reward() * forward_progress

        # foot_clearance_reward only judges SWING legs (rewards them for being elevated); nothing above judges STANCE legs, so a policy could still satisfy every term while sliding a planted foot along the ground the whole stance phase
        foot_slip_penalty = self._foot_slip_penalty()
        # touchdown_velocity_penalty MUST be computed before _feet_air_time_reward()
        touchdown_velocity_penalty = self._touchdown_velocity_penalty()
        # GATED by forward_progress pattern/reason as upright_reward/trot_symmetry_reward/tip_reward: ungated, correct swing-duration cadence is fully collectible (including the per-tick stance-cap penalty component
        feet_air_time_reward = self._feet_air_time_reward() * forward_progress

        # Flat, NOT gated by height_progress (unlike the stand task's, see ACTION_RATE_PENALTY_WEIGHT_RISING/STANDING's comment)
        action_rate_penalty = self._action_rate_penalty(action, WALK_ACTION_RATE_PENALTY_WEIGHT)

        # forward_velocity_reward weight raised 2.0 -> 5.0 : PPO_13000000_walk_policy_v3 measured foot_clearance_reward's weighted contribution at +0.99/step (near its 1.0 ceiling, trivially reached by permanently holding one leg up) against forward_velocity_reward's actual +0.0067/step (the robot wasn't moving, 0.000m traveled over 10s)
        angular_vel_penalty = self._angular_vel_penalty(WALK_ANGULAR_VEL_PENALTY_WEIGHT)

        # -(pitch - target)^2, already negative
        pitch_penalty = -((self._torso_pitch_rad() - WALK_TARGET_PITCH_RAD) ** 2)

        # roll_penalty WALK_ROLL_PENALTY_WEIGHT/_torso_roll_rad()'s own comments)
        roll_penalty = -(self._torso_roll_rad() ** 2)

        # Phase-gated EXTRA penalty for backward pitch specifically DURING the 'home'->standing rise  from the same investigation as HOME_START_FORWARD_LEAN_RAD above
        rise_backward_pitch_penalty = -(1.0 - climb_progress) * (min(0.0, self._torso_pitch_rad()) ** 2)

        # -(lateral_velocity)^2, -(yaw_rate)^2
        lateral_velocity_penalty = -(lateral_velocity ** 2)
        yaw_rate_penalty = -(self.data.sensordata[5] ** 2)

        # -(heading_deviation)^2
        yaw_diff = self._torso_yaw_rad() - self._episode_start_yaw
        yaw_diff = (yaw_diff + np.pi) % (2 * np.pi) - np.pi
        heading_deviation_penalty = -(yaw_diff ** 2)

        # SIMPLIFIED-REWARD EXPERIMENT user request: "only include forward movement, base height").
        walk_reward_total = (
            # RAISED 5.0 -> 25.0 testing purposes"
            25.0 * forward_velocity_reward
            + 0.5 * upright_reward
            + 1.0 * climb_posture_reward
            + 2.5 * height_reward
            # UNSTASHED unstash all the things we deleted"
            + WALK_HEIGHT_SAG_PENALTY_WEIGHT * height_sag_penalty
            + WALK_HEIGHT_OVERSHOOT_PENALTY_WEIGHT * height_overshoot_penalty
            + 0.0 * tip_reward
            + 1.0 * non_tip_penalty
            # RAISED 1.0 -> 2.0 FOOT_CLEARANCE_SIGMA_M
            + WALK_FRONT_CLEARANCE_WEIGHT * front_clearance_reward
            + WALK_BACK_CLEARANCE_WEIGHT * back_clearance_reward
            + 1.0 * foot_slip_penalty
            + 1.0 * touchdown_velocity_penalty
            + 0.5 * feet_air_time_reward
            + 1.0 * action_rate_penalty
            # angular_vel_penalty RESTORED 0.0 -> 1.0 code review): found zeroed here with no dated justification anywhere nearby, unlike every other weight in this return statement
            + 1.0 * angular_vel_penalty
            + 1.0 * WALK_PITCH_PENALTY_WEIGHT * pitch_penalty
            + 1.0 * WALK_ROLL_PENALTY_WEIGHT * roll_penalty
            + 1.0 * WALK_RISE_BACKWARD_PITCH_PENALTY_WEIGHT * rise_backward_pitch_penalty
            + 1.0 * WALK_LATERAL_VEL_PENALTY_WEIGHT * lateral_velocity_penalty
            + 1.0 * WALK_YAW_RATE_PENALTY_WEIGHT * yaw_rate_penalty
            + 1.0 * WALK_HEADING_DEVIATION_PENALTY_WEIGHT * heading_deviation_penalty
            # DROPPED investigation
            + gait_symmetry_weight * gait_symmetry_reward
            # ADDED investigation
            + WALK_SWING_FAIRNESS_WEIGHT * swing_fairness_penalty
            + WALK_SWING_AMPLITUDE_PENALTY_WEIGHT * swing_amplitude_penalty
            + WALK_CALF_ACTIVITY_PENALTY_WEIGHT * calf_activity_penalty
            + 0.02 * calf_swing_motion_reward
            + 1.0 * 0.1 # SURVIVAL BONUS: +0.1 per tick just for staying alive
            + 0.0 * self._common_penalties(action)
        )
        # SIMPLIFIED bound-only reward "reshape and simplify running (bound)...
        if self.gait_style == 'bound':
            # foot_usage_gate/thigh_rom_gate report on running_home/stand_s0_ms250_simple_alr_v3 and running_home/stand_s5_ms1000_simple_alr_v1
            min_foot_duty_cycle = float(np.min(self._contact_duty_cycle))
            foot_duty_deficit = max(0.0, WALK_BOUND_MIN_FOOT_DUTY_CYCLE - min_foot_duty_cycle)
            foot_usage_gate = np.exp(
                -(foot_duty_deficit ** 2) / (2 * WALK_BOUND_FOOT_USAGE_GATE_SIGMA ** 2))
            thigh_rom = (
                self._thigh_hinge_window.max(axis=0) - self._thigh_hinge_window.min(axis=0))
            thigh_rom_deficit = float(np.max(
                np.clip(WALK_BOUND_THIGH_ROM_FLOOR_RAD - thigh_rom, 0.0, None)))
            thigh_rom_gate = np.exp(
                -(thigh_rom_deficit ** 2) / (2 * WALK_BOUND_THIGH_ROM_GATE_SIGMA_RAD ** 2))
            calf_rom = (
                self._calf_hinge_window.max(axis=0) - self._calf_hinge_window.min(axis=0))
            calf_rom_deficit = float(np.max(
                np.clip(WALK_BOUND_CALF_ROM_FLOOR_RAD - calf_rom, 0.0, None)))
            calf_rom_gate = np.exp(
                -(calf_rom_deficit ** 2) / (2 * WALK_BOUND_CALF_ROM_GATE_SIGMA_RAD ** 2))
            calf_margin_deficit_s = float(np.max(
                np.clip(self._calf_margin_time - CALF_JOINT_MARGIN_GRACE_S, 0.0, None)))
            calf_joint_margin_gate = np.exp(
                -(calf_margin_deficit_s ** 2) / (2 * CALF_JOINT_MARGIN_GATE_SIGMA_S ** 2))
            symmetry_deficit = max(0.0, 1.0 - self._bound_symmetry_reward())
            raw_symmetry_gate = max(WALK_BOUND_SYMMETRY_GATE_FLOOR, np.exp(
                -(symmetry_deficit ** 2) / (2 * WALK_BOUND_SYMMETRY_GATE_SIGMA ** 2)))
            speed_blend = np.clip(
                (forward_progress - WALK_BOUND_SYMMETRY_SPEED_RATIO_START)
                / (WALK_BOUND_SYMMETRY_SPEED_RATIO_FULL - WALK_BOUND_SYMMETRY_SPEED_RATIO_START),
                0.0, 1.0)
            bound_symmetry_gate = 1.0 - speed_blend * (1.0 - raw_symmetry_gate)
            stance_straight_deficit_s = float(np.max(
                np.clip(self._calf_stance_straight_time - STANCE_STRAIGHT_GRACE_S, 0.0, None)))
            stance_straight_gate = max(STANCE_STRAIGHT_GATE_FLOOR, np.exp(
                -(stance_straight_deficit_s ** 2) / (2 * STANCE_STRAIGHT_GATE_SIGMA_S ** 2)))
            # calf_stance_side_gate / calf_thigh_tracking_gate direct user report + data investigation
            calf_side_deficit_s = float(np.max(
                np.clip(self._calf_wrong_side_time - CALF_STANCE_SIDE_GRACE_S, 0.0, None)))
            calf_stance_side_gate = max(CALF_STANCE_SIDE_GATE_FLOOR, np.exp(
                -(calf_side_deficit_s ** 2) / (2 * CALF_STANCE_SIDE_GATE_SIGMA_S ** 2)))
            calf_tracking_deficit_s = float(np.max(
                np.clip(self._calf_poor_tracking_time - CALF_THIGH_TRACKING_GRACE_S, 0.0, None)))
            calf_thigh_tracking_gate = max(CALF_THIGH_TRACKING_GATE_FLOOR, np.exp(
                -(calf_tracking_deficit_s ** 2) / (2 * CALF_THIGH_TRACKING_GATE_SIGMA_S ** 2)))
            walk_reward_total = (
                1.0 * forward_velocity_reward * foot_usage_gate * thigh_rom_gate
                * calf_rom_gate * calf_joint_margin_gate * bound_symmetry_gate
                * stance_straight_gate * calf_stance_side_gate * calf_thigh_tracking_gate)
        # Floor per-tick reward at 0 "fall early to minimize penalty" exploit, confirmed happening in the running_home_s5_ms1000_* bound-gait trainings: ep_rew_mean improved -3480 -> -63 over training while ep_len_mean COLLAPSED 800 -> 40 steps
        return max(0.0, walk_reward_total)

    def _ensure_viewer(self):
        if self.renderer is None:
            import mujoco.viewer
            self.renderer = mujoco.viewer.launch_passive(
                self.model, self.data, key_callback=self._on_key)
            # Group 3 = the simple collision-primitive geoms (capsules/box) kept alongside the real CAD visual meshes (group 2) for fast collision
            self.renderer.opt.geomgroup[3] = 0

    def _on_key(self, keycode):
        if keycode == 32:  # GLFW_KEY_SPACE
            self._paused = not self._paused

    def render(self):
        if self.render_mode != 'human':
            return
        self._ensure_viewer()
        self.renderer.sync()

    def close(self):
        if self.renderer is not None:
            self.renderer.close()
            self.renderer = None
